### ISSUE TITLE
New version crashes

### ISSUE THREAD

**Issue by thylo** [VeryCrazyDog/gnome-disable-gestures#3]
Hello, thank you for your extension. When you try to update the extension through https://extensions.gnome.org/extension/4049/disable-gestures-2021/ on Ubuntu 20.04.4 LTS with gnome 3.36.8 the updater crashes and disables the extension. It seems to be related to the latest commit.

**Comment by VeryCrazyDog** [comment]
That was strange. The source code didn't change. Any chance you can try uninstall first and install again to see if the extension work again?

**Comment by VeryCrazyDog** [comment]
Closing as there is no further feedback on this issue. If anyone facing this issue, try re-install the extension.

**Comment by thylo** [comment]
@VeryCrazyDog I'm very sorry for the late answer. I tried to uninstall and re-install the extension without succes. I ended up manually installing it from zip. I'll soon have to install it on another device. I'll keep you posted if I still encounter the bug.
