### ISSUE TITLE
gnome42 not working

### ISSUE THREAD

**Issue by lewis-gb** [VeryCrazyDog/gnome-disable-gestures#4]
trying to disable gestures on ubuntu22.04, but 22.04 is using gnome 42, and the gnome 41 version doesn't make gestures disabled, how could i do it on 22.04?

**Comment by lewis-gb** [comment]
just adapt the shell_version in extension.js works fine for 22.04

**Comment by VeryCrazyDog** [comment]
Released v4 which marked the extension compatible with GNOME 42.
