### ISSUE TITLE
Update extensions.gnome.org

### ISSUE THREAD

**Issue by PowerUser64** [VeryCrazyDog/gnome-disable-gestures#6]
I was trying to install this extension from extensions.gnome.org, but I noticed that the version there is for shell versions 44 and lower, despite the version in the repository being for version 45 and up. Should it be updated?

https://extensions.gnome.org/extension/4049/disable-gestures-2021/

**Comment by VeryCrazyDog** [comment]
Actually I attempted to publish a new version `v6` to extensions.gnome.org but got rejected because of the code did not meet the coding standard. Unfortunately I no longer have the hardware and environment to test the plugin even if I update the code, and that’s why the plugin didn’t got updated on the site.

Let me try revising the code and publish a new version again, but without testing. Hopefully there is no issue with the revise code 🥲

**Comment by PowerUser64** [comment]
I can test for you if you want! I already tested the master branch (as of when I posted this issue) and it works fine. If you push a change that you want me to test, just reply here and I'll try it out. I don't have experience with javascript or developing gnome extensions, but I know how to run them from source.

The plugin is so small, it's very strange that it doesn't meet their """coding standard.""" 😕 Does it say anything more than it doesn't meet the standard?

**Comment by PowerUser64** [comment]
Also, while we're on this topic, it might be good to update the repository url to refer to the extension's page on extensions.gnome.org. Right now the repository URL is not set.

| example from another repo | this repo |
| --- | --- |
| ![image](https://github.com/VeryCrazyDog/gnome-disable-gestures/assets/24578572/fd81d5cc-af9c-43bd-8043-c8475afcf965) | ![image](https://github.com/VeryCrazyDog/gnome-disable-gestures/assets/24578572/01937958-0a43-4141-91ba-71e3b5d0c800) |

(I can make another issue for this if you'd like)

**Comment by VeryCrazyDog** [comment]
> I can test for you if you want!

That will be great. New version v7 has been published to extensions.gnome.org. If you have the time please install the v7 extension and let me know if there is any issue.

> The plugin is so small, it's very strange that it doesn't meet their """coding standard.""" 😕 Does it say anything more than it doesn't meet the standard?

Yes, the reviewer did provide useful feedback. Maybe my word "coding standard" is not that appropriate. In simple word, the previous code did not properly released some resources when the extension disable. As most people using this extension are unlikely to disable the extension, that's probably why issues didn't surface. If you are interested in the details, there is [a page](https://blog.mecheye.net/2012/02/requirements-and-tips-for-getting-your-gnome-shell-extension-approved/) about the extension approval which you can read.

> it might be good to update the repository url to refer to the extension's page on extensions.gnome.org. Right now the repository URL is not set.

Thanks for point that out 😃, I have updated the URL and added tags to this repo for completeness.

**Comment by VeryCrazyDog** [comment]
As new version v7 has been published on extensions.gnome.org using code revised in commit ef41b66de7c5065e3b8d03358110dbb17e076c36, this issue is resolved. Closing the issue.

**Comment by PowerUser64** [comment]
New version works as expected, including disable functionality! Thanks for taking the time to do this!
