### ISSUE TITLE
update for gnome 46?

### ISSUE THREAD

**Issue by ozgur-as** [VeryCrazyDog/gnome-disable-gestures#7]
hello!

been using your extension for a long time, thank you for the updates through the years.

will you be updating to gnome 46 since ubuntu 24.04 lts is underway?

thanks!

**Comment by VeryCrazyDog** [comment]
Published a new release just now and is under review.

**Comment by VeryCrazyDog** [comment]
The new release is just active. You should be able to install that on GNOME 46.

**Comment by lokman2k5** [comment]
does not work on gnome 46
